base_link: 'yumi_body'

# =====================================================
left_gripper:
    end_effector_name: 'left_eef'  #ee group name

    #actuated joints in end effector
    joints : ['gripper_l_joint'] #gripper_l_joint_m

    #open position
    pregrasp_posture : [0.020] #max 0.0250
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.002] #min 0.0
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.12, 0, 0]

    #grasp_pose_to_eef_transform : [0,0,0,0,1.5708,0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'yumi_link_7_l'

# =====================================================
right_gripper:
    end_effector_name: 'right_eef'  #ee group name

    #actuated joints in end effector
    joints : ['gripper_r_joint']

    #open position
    pregrasp_posture : [0.020]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.002]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.12, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'yumi_link_7_r'
