yumi_node:
  debug: false
yumi_interface:
  debug: true
  bounded_solution: true
  module_name_left: tester_left
  module_name_right: tester_right
  end_effector_left: gripper_l_tcp
  end_effector_right: gripper_r_tcp